[build]
command = "sed -i \"s|API_FOOD_STRING|${API_URL}|g\" netlify.toml && yarn build"

[[redirects]]
from = "/api-food/*"
to = "API_FOOD_STRING:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
